server:
  port: 8080

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/book_store?createDatabaseIfNotExist=true
    username: root
    password: 1234

# app properties
com:
  app:
    cloudinary:
      name: dixswfj8d
      apiKey: 876943471796471
      apiSecret: XXlwrvw541Qmp83wIgDjxZpIoNQ
      rootFolder: book-store-images
    jwt:
      jwtSecret: ======================jwt=spring===========================
      jwtExpiration: 3 hour
      jwtRefreshExpiration: 5 hour